### ISSUE TITLE
"Support" drop-down tab needs to be reorganized

### ISSUE THREAD

**Issue by AndreaM** [CIDBioScience/felix.com#110]
Please restructure the Support by product, try to make each section more consistent. It's difficult to navigate as a list form without icons. 

The cid-inc.com Support tab is a better approach and easier to navigate- possibly use this as a template. Or perhaps a new approach could be stronger.

**Comment by loreguerra** [comment]
Icons added to the support drop down. I also grouped the items underneath each icon into another roll-over menu to reduce clutter. Let me know what you think. I can add small icons for warranty and distributor resources if you like. I think this is a good solution for now and it is consistent with the other two dropdown menus (products and applications). I can also make all icons a bit smaller (like CID) and then change the menus to be one column only to reduce some friction between roll-overs. Easy fixes for now.

These menus as well as CID menus can be thought through again for usability/flow later on.

**Comment by cmichelson** [comment]
Excellent, thank you! @loreguerra
