### ISSUE TITLE
Redo F950 Software Page

### ISSUE THREAD

**Issue by rahiensorei21** [CIDBioScience/felix.com#119]
Page that needs to be modified: http://www.felixinstruments.com/support/f-950-support/software

Location of modifications document: Z:\QUALITY ASSURANCE\F-950\F-950 Support Page.docx

The reason for the changes are because the current software page is confusing to the user and messy.

**Comment by loreguerra** [comment]
Page has been updated. http://www.felixinstruments.com/support/f-950-support/software
