### ISSUE TITLE
Put a picture of the F-750 with mangos on the product page

### ISSUE THREAD

**Issue by AndreaM** [CIDBioScience/felix.com#128]
Please put up a photo of the F-750 with mangos on the F-750 product page.
We have photo with apples and pears, but given our success with mangos and recent press, we should really be featuring this application on our F-750 product page.

I believe Grayson had taken images with mango in the past, along with many other types of fruit.

Best wishes,
Andrea

**Comment by loreguerra** [comment]
Photo has been added.
