### ISSUE TITLE
Change name to F-750 Mango Brochure

### ISSUE THREAD

**Issue by AndreaM** [CIDBioScience/felix.com#131]
The .pdf of the F-750 Mango Brochure is named correctly, but the link on the webpage under F-750 Application Notes > Mangoes says F-750 Brochure. Please rename to F-750 Mango Brochure

**Comment by loreguerra** [comment]
Name of brochure has been changed: http://www.felixinstruments.com/applications/f-750-applications/f-750-application-notes/item/215-application-note-mangoes
