### ISSUE TITLE
F-900 Support Page Update

### ISSUE THREAD

**Issue by rahiensorei21** [CIDBioScience/felix.com#132]
Here is a link to a google doc showing what the new F-900 support page should look like.
https://docs.google.com/a/cid-inc.com/document/d/1jVBgXe4qd_JL-SGgTUgNSMaXepffaVev4EErVJAfHC0/edit?usp=sharing

**Comment by loreguerra** [comment]
Just to be clear, I will be modifying this page: http://felixinstruments.com/support/f-900-support/software

Please correct me if I'm wrong. The other ticket with a similar request directly references the software page, so I'd like to 100% sure I'm reading you correctly.

**Comment by loreguerra** [comment]
Support page has been updated: http://www.felixinstruments.com/support/f-900-support/software
