### ISSUE TITLE
F-900 Specifications on website are incomplete

### ISSUE THREAD

**Issue by AndreaM** [CIDBioScience/felix.com#133]
Please double check and update all F-900 specifications. They are incomplete. Make sure accuracy is listed for each sensor.

\\CIDSERVER1\V2cid\SALES\Lock Out Specifications\Felix Instruments

**Comment by loreguerra** [comment]
Accuracy specs added to F-900. Checked F-950 and updated a few form fields based on what was in the same specs folder.

F-750 spec sheet has almost completely different tables than on the site. Let me know if you want that updated to match as well.
