### ISSUE TITLE
F-900 text on webpage incorrect 

### ISSUE THREAD

**Issue by AndreaM** [CIDBioScience/felix.com#134]
existing: In addition to ethylene sensing the F-900 has been designed to carry an additional sensor that measures Carbon Dioxide (CO2).

should read: In addition to sensing ethylene, F-900 has been designed to carry sensors for measurements of Carbon Dioxide (0-2000 ppm or 0-20%) and Oxygen (0-100%). 

http://felixinstruments.com/products/ethylene-analysis/f-900-portable-ethylene-analyzer

**Comment by loreguerra** [comment]
Text change has been made.
