### ISSUE TITLE
750 FAQ Update under Support tab

### ISSUE THREAD

**Issue by AndreaM** [CIDBioScience/felix.com#138]
The FAQ currently has an entry:
What do I do if F-750 SD card becomes corrupted? 
 If your F-750 keeps indicating that is it "checking SD card" or is creating 0 byte files, this is likely an indicator of a corrupt SD card.  Remove the SD card and insert it into a computer.
Back up the "models" folder and .dat files on the SD card to your PC.
Do not have Windows scan and repair the SD card.  Rather, use the following SD card manufacturers tool: https://www.sdcard.org/downloads/formatter_4/index.html  
Reload the "Models" folder on the SD card.  Do not reload the .dat files.  Then, re-install the SD card in the F-750 device and power it on.    
Always wait for the F-750 to completely power off and shut down before removing the SD card.  

It should read:
What do I do if the F-750 SD card becomes corrupted? 
 If your F-750 keeps indicating that it is "checking SD card" or is creating 0 byte length files, this is likely an indicator of a corrupt SD card.  Remove the SD card and insert it into a computer.
Copy the "Models" folder and .dat files on the SD card to your PC where you can find them later.
Do not have Windows scan and repair the SD card.  Rather, use the following SD card manufacturers tool: https://www.sdcard.org/downloads/formatter_4/index.html  
Copy the "Models" folder back onto the SD card.  The .dat files are your previous data and do not need to be copied back to the SD card.  Then re-install the SD card into the F-750 and turn the power on. 
Always wait for the F-750 to completely power off and shut down before removing the SD card.

**Comment by loreguerra** [comment]
Updated 12/17, edited by Brie, and edited again on 12/21 due to formatting issues.
