### ISSUE TITLE
New staff headshots to contact page

### ISSUE THREAD

**Issue by AndreaM** [CIDBioScience/felix.com#139]
New photos were taken to replace current staff pictures. Please update!

http://felixinstruments.com/contactus/about-us/meet-our-team

**Comment by JudithEdwards** [comment]
http://felixinstruments.com/contactus/about-us/meet-our-team

Let me know if you need help identifying people in the photos.

**Comment by AndreaM** [comment]
Let's also arrange the staff by department after/as you are replacing photos.

**Comment by loreguerra** [comment]
I'm missing photos for Suzy, Sherri, Charlie and Chauncey. Do you want me to update the photos anyway and add the others later?

**Comment by JudithEdwards** [comment]
Yes, please update now. I wonder if there are raw files somewhere else. If not, would you mind taking the photos so they match the others? 

Best,

Judith

**Comment by loreguerra** [comment]
I'll search for the raw files. 

I need names and titles for these two photos. Also, let me know (eventually) how you'd like the photos ordered.

![967a1783](https://cloud.githubusercontent.com/assets/16310498/11968311/e2646f22-a8bf-11e5-92e2-095f0312db6e.jpg)
![967a1794](https://cloud.githubusercontent.com/assets/16310498/11968310/e2645438-a8bf-11e5-861c-4c353f1e6850.jpg)

**Comment by JudithEdwards** [comment]
1. Beth Skiles, Office Administrator

2. Leah Kooiman, Engineering Intern

**Comment by JudithEdwards** [comment]
We'll need to take a photo of Carlee, as well, and add that to the website. Each person has a department listed in a grey bubble. Here is how the order should be: 

Administration
(Add Beth Skiles to this category)
(Add Yu-Yun to this category)

Sales & Marketing
(Please change my title to Marketing Manager | Sales Administrator
Support
(Add Carlee Michelson to this category)
Engineering
Quality Assurance
Production
Accounting
Shipping & Receiving

**Comment by JudithEdwards** [comment]
Change Suzy's title to: Distributor Manager

**Comment by loreguerra** [comment]
That's all done. I'll work on the other photos.

**Comment by JudithEdwards** [comment]
Wonderful! And, you'll need to add yourself, of course! :)
