### ISSUE TITLE
Different specifications for F-750 on web than lock out spec sheet

### ISSUE THREAD

**Issue by loreguerra** [CIDBioScience/felix.com#140]
F-750 on the website lists different specifications than on the spec sheet in Lock Out Specs. Let me know if you want the website changed to match the Lock out specs.

**Comment by JudithEdwards** [comment]
Yes, please! We've been wanting this for a while! Thank you for noticing.

**Comment by loreguerra** [comment]
Specs updated on website.http://www.felixinstruments.com/products/produce-quality/f-750-produce-quality-meter
