### ISSUE TITLE
Change the way we allow users to download software

### ISSUE THREAD

**Issue by lerudcid** [CIDBioScience/felix.com#144]
currently we direct the user to a separate webpage.
![image](https://cloud.githubusercontent.com/assets/3239225/12212250/05da9386-b61d-11e5-8fbd-288ef8e18753.png)

However we really only want to supply the user with the file at the bottom of the webage, ie the offline installer. We need the "online installer" setup.exe and this url for the autoupdate functionally to work. The two download links in theory point to the same build version, but this has not always been the case. The bottom link has no version information nor release date information.

If we put a download button on the felix software page, the user can access this file and stay on a themed cms page.

**Comment by loreguerra** [comment]
@lerudcid Is this what you mentioned earlier? Can you finish typing the title of the ticket so I get some context?

**Comment by lerudcid** [comment]
Sorry, not sure how the title got truncated.

The basic idea is to hide the existing download page for each software product. And provide a link on a cms themed page to the file currently provided in the footer. 


The existing download page must remain for the software to phone home and get an incremental update.

**Comment by loreguerra** [comment]
Page has been edited. The other two support pages are set up differently and point to files instead of the separate page.

http://www.felixinstruments.com/support/f-750-support/software
