### ISSUE TITLE
Replace intensely photoshopped 2L chamber image with a real photo

### ISSUE THREAD

**Issue by AndreaM** [CIDBioScience/felix.com#152]
http://felixinstruments.com/products/ethylene-analysis/accessories/2l-sample-chamber

I believe we have actual photos of this chamber. Please replace the opening image with an actual photo.

**Comment by loreguerra** [comment]
This is all I found. Should I replace with this and plan on reshooting?
![f900-chamber](https://cloud.githubusercontent.com/assets/16310498/12523733/791b0f7e-c10d-11e5-985b-b42f40f79dd8.jpg)

**Comment by AndreaM** [comment]
Yes, I think that's a good move for now.

**Comment by loreguerra** [comment]
Photo has been changed. I'll make a note to reshoot this soon.

**Comment by loreguerra** [comment]
Randomly found photos for this and edited them. They're on the site. 

http://www.felixinstruments.com/products/ethylene-analysis/accessories/chamber-attachment-wand
