### ISSUE TITLE
Please post calibration schedules online

### ISSUE THREAD

**Issue by AndreaM** [CIDBioScience/felix.com#153]
Salesteam is top priority, and we should make a section for it on the webpage too. Maybe under Support?

You can separate these into 900 and 950. This is from my distributor sales training presentation and Suzy requested that we put it online.
[F-900 and F-950 Calibration chart.pptx](https://github.com/CIDBioScience/felix.com/files/101514/F-900.and.F-950.Calibration.chart.pptx)

Also in samba \\CIDSERVER1\V2cid\SALES\Product comparison Charts

**Comment by loreguerra** [comment]
Added to salesteam under Specifications Documents and added to the regular site as a table under Support. Let me know if you want any of that changed.
