### ISSUE TITLE
Link for Netherlands distributor not working. 

### ISSUE THREAD

**Issue by JudithEdwards** [CIDBioScience/felix.com#154]
Should be: http://www.dqfs.nl/

**Comment by loreguerra** [comment]
When I click on the link above, it goes to a reserved domain. 

There are two pages for distributors. One doesn't have Netherlands and one has an entry for BCON: www.bcon-instruments.nl

It's impossible to add distributors right now, but let me know if you still want BCON to link to http://www.dqfs.nl/.

**Comment by JudithEdwards** [comment]
Hi Lorena, 

Are you looking at the Felix site? Under Netherlands on the Felix website I am only seeing DQFS and the link doesn't work. It should be replaced with http://www.dqfs.nl/. 

Thanks,

Judith

**Comment by loreguerra** [comment]
oops. No, I wasn't.

**Comment by JudithEdwards** [comment]
http://www.qcone.com/

**Comment by loreguerra** [comment]
Change has been made.
