### ISSUE TITLE
Calibration Kit photos and description are incorrect.

### ISSUE THREAD

**Issue by AndreaM** [CIDBioScience/felix.com#156]
Remove Current F-900 calibration kit and replace with new photos and description from Price List, 900CK

http://www.felixinstruments.com/products/ethylene-analysis/accessories/calibration-kit is out of date.

[2016 Felix Instruments Pricelist v1.docx](https://github.com/CIDBioScience/felix.com/files/118083/2016.Felix.Instruments.Pricelist.v1.docx)
[2016 Felix Instruments Pricelist v1.pdf](https://github.com/CIDBioScience/felix.com/files/118082/2016.Felix.Instruments.Pricelist.v1.pdf)

**Comment by loreguerra** [comment]
Just to clarify - this is the image you want on the website instead?
<img width="181" alt="screen shot 2016-02-04 at 11 34 26 am" src="https://cloud.githubusercontent.com/assets/16310498/12827196/542f80e8-cb33-11e5-83df-5ea20859672b.png">

**Comment by AndreaM** [comment]
Yes

 

--
Andrea Melnychenko
Application Scientist & Sales Director
 
t +1 (360) 833-8835 x204
m +1 (971) 506-6796
e amelnychenko@ <http://www.cid-inc.com/> cid-inc.com
 
CID Bio-Science, Inc.
1554 NE 3rd Avenue
Camas, WA 98607 USA

**Comment by loreguerra** [comment]
I think it'll be much faster to take a new photo. Should I ask Beth about a kit?

**Comment by AndreaM** [comment]
Yes, talk to Beth and/or the support scientists about a kit.

**Comment by loreguerra** [comment]
will be taking a new photo next week.

**Comment by loreguerra** [comment]
Randomly found this on the search for something else entirely.

I can leave the instrument in or photoshop it out. Let me know which you prefer.

<img width="840" alt="screen shot 2016-02-10 at 11 09 20 am" src="https://cloud.githubusercontent.com/assets/16310498/12958472/c8d51824-cfe6-11e5-82c0-fbf25093ab7d.png">

**Comment by cmichelson** [comment]
That is the same tank and regulator we have on the shelf, looks up-to-date.

**Comment by loreguerra** [comment]
added to the site. Thanks @cmichelson !
